version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresData:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5555:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pawan
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgresData: # named volumes can be managed easier using docker-compose